name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm install
      
      - name: Build app
        run: npm run build
      
      - name: Deploy to S3
        uses: reggionick/s3-deploy@v3
        with:
          args: --acl public-read --delete
          local_dir: dist
          bucket: ryanbray.io
          region: us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
