name: Deploy to S3

on:
  push:
    branches:
      - main
      
env:
  AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
  AWS_REGION: ${{ secrets.BUCKET_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to S3 bucket
        uses: reggionick/s3-deploy@v3
        with:
          args: --acl public-read --delete
          local_dir: dist
          bucket: ${{ env.S3_BUCKET_NAME }}
          folder: ${{ env.S3_BUCKET_PATH }}
